### ISSUE TITLE
Error de autorización para Google Sign-In

### ISSUE THREAD

**Issue by lcs1001** [lcs1001/Gestion_Aulas_Informatica#28]
![image](https://user-images.githubusercontent.com/44766371/79770806-30e0e200-832e-11ea-9f5b-bfb2ebc7acdf.png)

**Comment by lcs1001** [comment]
Solucionado configurando correctamente la URI de origen del cliente web desde la [consola de desarrollo de Google](console.developers.google.com), copiando el Id de Cliente y cambiándolo en el código del index.html. 
![image](https://user-images.githubusercontent.com/44766371/79771863-ac8f5e80-832f-11ea-8c24-9d0bb565c28d.png)

**Comment by jmaudes** [comment]
Que bien!!
Ya lo demas deberia de tener menos sorpresas o ninguna

Saludos

Jesus
